### ISSUE TITLE
Snake speed seems to depend on frame rate

### ISSUE THREAD

**Issue by Moxinilian** [nag763/texas-snake#1]
Hello!

The speed of the snake seems to depend on the framerate, which can make the game unplayably fast.

I believe this is because you do not take the delta time between frames into account when [computing the speed of the snake](https://github.com/nag763/texas-snake/blob/e1dc7c8b03fd4977846cbc342e460daef7d81bb6/snake/src/systems/running.rs#L16). This should be easily fixed by multiplying the speed with [the delta time between frames](https://docs.rs/bevy/latest/bevy/time/struct.Time.html#method.delta_seconds).

**Comment by nag763** [comment]
Hello, and thanks for that report.

I seen many complaint in this regard. Thanks for that solution.

In all honesty, I think the main issue was that my first queue component is always colliding with the snake head when it is too slow. Since every queue member takes the position of the former one, and the first one the last position of the snake, if the snake didn't move of SNAKE_SIZE (SNAKE_SIZE/2 + QUEUE_SIZE(=SNAKE_SIZE)/2), they will collide.

Since the snake head still has to be visible by most users, I need to make a speed sufficient enough to not collide the snake head and the first queue member.

I think the best (or if you ever have a better one in mind), is to not add "Collider" to the first queue member.

**Comment by nag763** [comment]
Fixed in https://github.com/nag763/texas-snake/commit/27386534ebffd5e66583c3b223174e13338d715a

**Comment by Moxinilian** [comment]
Thank you, although I strongly recommend still using the delta time between frames. Otherwise, your game will still be unplayable on sufficiently performant hardware (or particularly slow on less performant hardware).

**Comment by nag763** [comment]
Hmm makes sense, thanks very much for that tip, much appreciated
